version: '3.1'

services:
  test-db:
    image: postgres:15-alpine
    container_name: ${DOCKER_PREFIX}_test-db
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: test_db
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    volumes:
      - test-db-volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_EXPOSE}:${DB_PORT}

networks:
  default:
    driver: bridge
    name: ${DOCKER_PREFIX}-network

volumes:
  test-db-volume: 
    name: ${DOCKER_PREFIX}_test-db_volume